version: '3'
services:
  segment:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9999:9999"
    container_name: segment
  portal:
    build:
      context: ../../DevLab/segment-portal
      dockerfile: Dockerfile
    ports:
      - "80:80"
    links:
      - segment
    container_name: portal
    depends_on: [segment]