version: '3'
services:
  seg_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9878:9878"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
  redis:
    image: "segment_redis:latest"
    ports:
      - "6379:6379"