version: '3'
services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9876:9876"
    environment:
      MYSQL_URL: mysql   # mysql容器地址
      MYSQL_PORT: 3306   # mysql容器端口
    depends_on:
      - mysql
  mysql:
    image: "mysql:5.7"
    ports:
      - "33060:3306"   # 将容器3306端口映射到宿主机的33060端口
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=seg
    volumes:
      - D:/DevelopSpace/segment/mysql/data:/var/lib/mysql # mysql容器数据存储目录挂载到宿主机固定目录下，所有该镜像下的容器都共用数据库数据
