myapp:
  dict-path: /app/config/user.dict
  config-path: /app/config
logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
spring:
  datasource:
    url: jdbc:h2:file:/app/h2db
    username: sa
    password: password
    driverClassName: org.h2.Driver