myapp:
  dict-path: config/user.dict
  word-path: config/latest_word.csv
  st-path: config/latest_st.csv
  synonyms-path: config/latest_synonyms.csv
  config-path: config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seg?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
# 后端统一地址前缀
server:
  servlet:
    context-path: /seg
