myapp:
  dict-path: config/user.dict
  word-path: config/latest_word.csv
  st-path: config/latest_st.csv
  synonyms-path: config/latest_synonyms.csv
  config-path: config

spring:
  redis:
    host: localhost
    port: 6379
